language: python
python:
  - '3.6'

before_install:
  - pip install -U pip
  - pip install poetry
  - pip install codecov

install:
  - poetry install

script:
  - poetry run mypy src
  - poetry run pytest

after_success:
  - codecov
