language: python
python:
  - '3.6'

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install poetry
  - pip install codecov

install:
  - poetry install

script:
  - poetry run mypy src
  - poetry run pytest

after_success:
  - codecov
